# Generated by Django 4.0.3 on 2022-04-12 13:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='joined_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 12, 13, 5, 36, 467931, tzinfo=utc)),
        ),
    ]
