# Generated by Django 4.0.3 on 2022-04-20 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='total',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
