# Generated by Django 4.0.3 on 2022-05-05 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0002_alter_bookmark_user_alter_image_pet_alter_pet_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='price',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AlterField(
            model_name='pet',
            name='total',
            field=models.CharField(default=1, max_length=20),
        ),
    ]
