// auth action type
export const LOGGING_IN = "LOGGING_IN"
export const LOGGING_IN_SUCCESS = "LOGGING_IN_SUCCESS"
export const LOGGING_IN_FAIL = "LOGGING_IN_FAIL"

export const LOGGING_OUT = "LOGGING_OUT"
export const LOGGING_OUT_SUCCESS = "LOGGING_OUT_SUCCESS"
export const LOGGING_OUT_FAIL = "LOGGING_OUT_FAIL"

export const REGISTERING = "REGISTERING"
export const REGISTERING_SUCCESS = "REGISTERING_SUCCESS"
export const REGISTERING_FAIL = "REGISTERING_FAIL"

export const CHANGE_PASSWORD = "CHANGE_PASSWORD"
export const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS"
export const CHANGE_PASSWORD_FAIL = "CHANGE_PASSWORD_FAIL"

export const CHECK_EMAIL = "CHECK_EMAIL"
export const CHECK_EMAIL_SUCCESS = "CHECK_EMAIL_SUCCESS"
export const CHECK_EMAIL_FAIL = "CHECK_EMAIL_FAIL"

export const CHECK_USERNAME = "CHECK_USERNAME"
export const CHECK_USERNAME_SUCCESS = "CHECK_USERNAME_SUCCESS"
export const CHECK_USERNAME_FAIL = "CHECK_USERNAME_FAIL"

export const SEND_EMAIL = "SEND_EMAIL"
export const SEND_EMAIL_SUCCESS = "SEND_EMAIL_SUCCESS"
export const SEND_EMAIL_FAIL = "SEND_EMAIL_FAIL"

export const DELETE_ACCOUNT = "DELETE_ACCOUNT"
export const DELETE_ACCOUNT_SUCCESS = "DELETE_ACCOUNT_SUCCESS"
export const DELETE_ACCOUNT_FAIL = "DELETE_ACCOUNT_FAIL"

// breed action type
export const GET_BREEDS = "GET_BREEDS"
export const GET_BREEDS_SUCCESS = "GET_BREEDS_SUCCESS"
export const GET_BREEDS_FAIL = "GET_BREEDS_FAIL"

export const ADD_BREED = "ADD_BREED"
export const ADD_BREED_SUCCESS = "ADD_BREED_SUCCESS"
export const ADD_BREED_FAIL = "ADD_BREED_FAIL"

// pet action type
export const ADD_PET = "ADD_PET"
export const ADD_PET_SUCCESS = "ADD_PET_SUCCESS"
export const ADD_PET_FAIL = "ADD_PET_FAIL"

export const GET_PET = "GET_PET"
export const GET_PET_SUCCESS = "GET_PET_SUCCESS"
export const GET_PET_FAIL = "GET_PET_FAIL"

export const GET_PETS = "GET_PETS"
export const GET_PETS_SUCCESS = "GET_PETS_SUCCESS"
export const GET_PETS_FAIL = "GET_PETS_FAIL"

export const UPDATE_PET = "UPDATE_PET"
export const UPDATE_PET_SUCCESS = "UPDATE_PET_SUCCESS"
export const UPDATE_PET_FAIL = "UPDATE_PET_FAIL"

export const DELETE_PET = "DELETE_PET"
export const DELETE_PET_SUCCESS = "DELETE_PET_SUCCESS"
export const DELETE_PET_FAIL = "DELETE_PET_FAIL"

// pet image action type
export const ADD_PET_IAMGE = "ADD_PET_IAMGE"
export const ADD_PET_IAMGE_SUCCESS = "ADD_PET_IAMGE_SUCCESS"
export const ADD_PET_IAMGE_FAIL = "ADD_PET_IAMGE_FAIL"

export const DELETE_PET_IAMGE = "DELETE_PET_IAMGE"
export const DELETE_PET_IAMGE_SUCCESS = "DELETE_PET_IAMGE_SUCCESS"
export const DELETE_PET_IAMGE_FAIL = "DELETE_PET_IAMGE_FAIL"


// bookmark action type
export const ADD_BOOKMARK = "ADD_BOOKMARK"
export const ADD_BOOKMARK_SUCCESS = "ADD_BOOKMARK_SUCCESS"
export const ADD_BOOKMARK_FAIL = "ADD_BOOKMARK_FAIL"

export const GET_BOOKMARK = "GET_BOOKMARK"
export const GET_BOOKMARK_SUCCESS = "GET_BOOKMARK_SUCCESS"
export const GET_BOOKMARK_FAIL = "GET_BOOKMARK_FAIL"

export const GET_BOOKMARKS = "GET_BOOKMARKS"
export const GET_BOOKMARKS_SUCCESS = "GET_BOOKMARKS_SUCCESS"
export const GET_BOOKMARKS_FAIL = "GET_BOOKMARKS_FAIL"

export const DELETE_BOOKMARK = "DELETE_BOOKMARK"
export const DELETE_BOOKMARK_SUCCESS = "DELETE_BOOKMARK_SUCCESS"
export const DELETE_BOOKMARK_FAIL = "DELETE_PET_FAIL"

// profile action type"
export const GET_PROFILE = "GET_PROFILE"
export const GET_PROFILE_SUCCESS = "GET_PROFILE_SUCCESS"
export const GET_PROFILE_FAIL = "GET_PROFILE_FAIL"

export const UPDATE_PROFILE = "UPDATE_PROFILE"
export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS"
export const UPDATE_PROFILE_FAIL = "UPDATE_PROFILE_FAIL"

// messages and errors
export const SHOW_MESSAGE = "SHOW_MESSAGE"
export const SHOW_ERROR = "SHOW_ERROR"
export const RESET_MESSAGES = "RESET_MESSAGES"
export const RESET_ERRORS = "RESET_ERRORS"